# -*- coding: utf-8 -*-
"""test_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o-3Dfb9mwjn4azR2-uPDx7ibB1vPo5z0
"""

import pytest
import requests
from generate_response import generer_reponse

# Import conditionnel pour gérer les différentes versions
try:
    from fastapi.testclient import TestClient
    from main import app
    
    # Créer le client avec gestion des versions différentes
    try:
        client = TestClient(app)
    except TypeError:
        # Fallback pour versions plus récentes
        import httpx
        from fastapi import FastAPI
        client = TestClient(app=app)
        
except ImportError as e:
    print(f"Erreur import TestClient: {e}")
    client = None

def test_generer_reponse_mock():
    # Par défaut, les modèles IA sont désactivés (mode fallback)
    result = generer_reponse("Bonjour", "positif")
    assert "Merci beaucoup" in result

def test_api_health():
    """Test que l'API démarre correctement"""
    if client is None:
        print("⚠️ TestClient non disponible, test ignoré")
        return
        
    response = client.get("/docs")
    assert response.status_code == 200

def test_analyse_endpoint():
    """Test de l'endpoint /analyse"""
    if client is None:
        print("⚠️ TestClient non disponible, test ignoré")
        return
        
    test_data = {"texte": "Ce produit est fantastique!"}
    response = client.post("/analyse", json=test_data)
    
    assert response.status_code == 200
    data = response.json()
    assert "sentiment" in data
    assert "reponse" in data
    # En mode fallback, on devrait avoir une réponse prédéfinie
    assert len(data["reponse"]) > 10

if __name__ == "__main__":
    # Exécuter les tests
    test_generer_reponse_mock()
    test_api_health()
    test_analyse_endpoint()
    print("✅ Tous les tests sont passés!")
